# Generated by Django 4.2.7 on 2025-12-18 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_aboutpage_aboutvalue_abouttimelineitem_contactinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMissionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Mission', max_length=200)),
                ('content', models.TextField(help_text='Mission statement')),
                ('is_active', models.BooleanField(default=True, help_text='Only active content will be displayed')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Mission Section',
                'verbose_name_plural': 'About Mission Sections',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutStorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Story', max_length=200)),
                ('content', models.TextField(help_text='Main story content for the About page')),
                ('is_active', models.BooleanField(default=True, help_text='Only active content will be displayed')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Story Section',
                'verbose_name_plural': 'About Story Sections',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutTimelineSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Journey', max_length=200)),
                ('subtitle', models.TextField(blank=True, help_text='Subtitle for timeline section')),
                ('is_active', models.BooleanField(default=True, help_text='Only active content will be displayed')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Timeline Section Header',
                'verbose_name_plural': 'About Timeline Section Headers',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutValuesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Core Values', max_length=200)),
                ('subtitle', models.TextField(blank=True, help_text='Subtitle for values section')),
                ('is_active', models.BooleanField(default=True, help_text='Only active content will be displayed')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Values Section Header',
                'verbose_name_plural': 'About Values Section Headers',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutVisionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Vision', max_length=200)),
                ('content', models.TextField(help_text='Vision statement')),
                ('is_active', models.BooleanField(default=True, help_text='Only active content will be displayed')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Vision Section',
                'verbose_name_plural': 'About Vision Sections',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'ordering': ['-updated_at'], 'verbose_name': 'About Page (Legacy)', 'verbose_name_plural': 'About Page (Legacy)'},
        ),
        migrations.RemoveField(
            model_name='abouttimelineitem',
            name='about_page',
        ),
        migrations.RemoveField(
            model_name='aboutvalue',
            name='about_page',
        ),
        migrations.AddField(
            model_name='abouttimelineitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='abouttimelineitem',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only active timeline items will be displayed'),
        ),
        migrations.AddField(
            model_name='abouttimelineitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='aboutvalue',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='aboutvalue',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only active values will be displayed'),
        ),
        migrations.AddField(
            model_name='aboutvalue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
