# Generated by Django 4.2.7 on 2025-12-18 22:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_aboutmissionsection_aboutstorysection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'ordering': ['-updated_at'], 'verbose_name': 'About Page (Legacy)', 'verbose_name_plural': '📄 About - Legacy (Deprecated)'},
        ),
        migrations.AlterModelOptions(
            name='aboutstorysection',
            options={'ordering': ['-updated_at'], 'verbose_name': 'About Story Section', 'verbose_name_plural': 'About - Story Sections'},
        ),
        migrations.AlterModelOptions(
            name='abouttimelineitem',
            options={'ordering': ['order', 'year'], 'verbose_name': 'Timeline Item', 'verbose_name_plural': 'About - Timeline Items'},
        ),
        migrations.AlterModelOptions(
            name='abouttimelinesection',
            options={'ordering': ['-updated_at'], 'verbose_name': 'About Timeline Section Header', 'verbose_name_plural': 'About - Timeline Headers'},
        ),
        migrations.AlterModelOptions(
            name='aboutvalue',
            options={'ordering': ['order', 'id'], 'verbose_name': 'About Value', 'verbose_name_plural': 'About - Values'},
        ),
        migrations.AlterModelOptions(
            name='aboutvaluessection',
            options={'ordering': ['-updated_at'], 'verbose_name': 'About Values Section Header', 'verbose_name_plural': 'About - Values Headers'},
        ),
        migrations.AlterModelOptions(
            name='aboutvisionsection',
            options={'ordering': ['-updated_at'], 'verbose_name': 'About Vision Section', 'verbose_name_plural': 'About - Vision Sections'},
        ),
        migrations.AlterModelOptions(
            name='heroimage',
            options={'ordering': ['-is_active', '-created_at'], 'verbose_name': 'Hero Image', 'verbose_name_plural': '🖼️ Hero Images'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-created_at'], 'verbose_name': 'Testimonial', 'verbose_name_plural': '⭐ Testimonials'},
        ),
        migrations.CreateModel(
            name='BlogPostVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_type', models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('upload', 'Uploaded Video')], default='youtube', help_text='Select the type of video', max_length=20)),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL (e.g., https://www.youtube.com/watch?v=xxxxx or https://vimeo.com/xxxxx)')),
                ('video_file', models.FileField(blank=True, help_text='Upload a video file (MP4, WebM, or OGG)', null=True, upload_to='blog_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'])])),
                ('title', models.CharField(blank=True, help_text='Video title', max_length=200)),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional custom thumbnail for the video', null=True, upload_to='blog_video_thumbnails/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.blogpost')),
            ],
            options={
                'verbose_name': 'Blog Post Video',
                'verbose_name_plural': 'Blog Post Videos',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload an image to include in the blog post', upload_to='blog_content_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])])),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=300)),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.blogpost')),
            ],
            options={
                'verbose_name': 'Blog Post Image',
                'verbose_name_plural': 'Blog Post Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
