# Generated by Django 4.2.7 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_aboutpage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook page URL', max_length=200),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter/X profile URL', max_length=200),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL', max_length=200),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL', max_length=200),
        ),
    ]

