# Generated by Django 4.2.7 on 2025-12-19 11:24

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_contactinformation_social_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the gallery item', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of the event or item')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', help_text='Select whether this is an image or video', max_length=10)),
                ('event_type', models.CharField(choices=[('meeting', 'Meeting'), ('celebration', 'Celebration'), ('workshop', 'Workshop'), ('community', 'Community Event'), ('award', 'Award Ceremony'), ('other', 'Other')], default='other', help_text='Type of event this media is from', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Upload an image for the gallery', null=True, upload_to='gallery_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])])),
                ('video_type', models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('upload', 'Uploaded Video')], default='youtube', help_text='Type of video (only for video media type)', max_length=20)),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL (e.g., https://www.youtube.com/watch?v=xxxxx)')),
                ('video_file', models.FileField(blank=True, help_text='Upload a video file (MP4, WebM, or OGG)', null=True, upload_to='gallery_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'])])),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional custom thumbnail for videos', null=True, upload_to='gallery_video_thumbnails/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('event_date', models.DateField(blank=True, help_text='Date when the event occurred', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured items will be displayed prominently')),
                ('is_active', models.BooleanField(default=True, help_text='Only active items will be displayed in the gallery')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': '🖼️ Gallery Items',
                'ordering': ['order', '-event_date', '-created_at'],
            },
        ),
    ]
